### ISSUE TITLE
How to do validations?

### ISSUE THREAD

**Issue by caplod** [huacnlee/rails-settings-cached#153]
I want to validate the settings. How can I do this? 
I tried the following
```ruby
class Setting < RailsSettings::Base
  include ActiveModel::Validations
  source Rails.root.join("config/app.yml")
  attr_reader :tax_percentage
  validates :tax_percentage, numericality: { greater_than: 1 }
end
```

but that gives me

```ruby
>> Setting.tax_percentage = 18
Traceback (most recent call last):
        1: from (irb):9
ActiveRecord::RecordInvalid (Gültigkeitsprüfung ist fehlgeschlagen: Tax percentage ist keine Zahl)
```

**Comment by CKolkey** [comment]
Seconded for this :)

**Comment by Ex-Ark** [comment]
@caplod  @CKolkey  if you're still looking here's what I tried

Two solutions that works: 

- with `with_options`
```ruby
# RailsSettings Model
class Setting < RailsSettings::Base
  field :tax_percentage
  field :state

  with_options if: -> { var == 'tax_percentage' } do |on_condition|
    on_condition.validates_numericality_of :value, greater_than: 1
    # you can add anothers validators on tax_percentage here
  end

  with_options if: -> { var == 'state' } do |on_condition|
    on_condition.validates_inclusion_of :value, in: ['Open', 'Closed']
    # you can add anothers validators on state here
  end
end
```

- with `if: -> {}` on each validate statement
```ruby
class Setting < RailsSettings::Base
  field :tax_percentage
  field :state
  validates :value, numericality: { greater_than: 1 }, if: -> { var == 'tax_percentage' }
  validates_inclusion_of :value, in: ['Open', 'Closed'], if: -> { var == 'state' }
  # you can add anothers validators with if condition at the end to specify the field
end
```

It works like that : 

```ruby
Setting.state = 'AAA'
# ActiveRecord::RecordInvalid (Validation failed : Value is not included in the list)
Setting.state = 'Closed'
# Setting Load (0.5ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`var` = 'state' LIMIT 1
# => 'Closed'
```

**Comment by mashedkeyboard** [comment]
@Ex-Ark's start was helpful for me, but I found that (weirdly, only in development and production - not in my test environment) `attribute_changed_in_place?` returned false for the `value` on the record in the `NumericalityValidator` (https://github.com/rails/rails/blob/cbfbb2c9f9d5392869e755fbbc646ec19c05a54f/activemodel/lib/active_model/validations/numericality.rb#L127), which was causing the validations to always fail. After some investigation, it looks like they tried to validate the YAML string rather than the number - `--- 0\n` rather than `0`, for instance. To fix this, I implemented a custom validator that wraps the `NumericalityValidator`, but takes away the actual `Setting` record from it:

```ruby
class NumericSettingValidator < ActiveModel::Validator
    def validate(record)
      fake_record = OpenStruct.new(errors: ActiveModel::Errors.new(record))
      ActiveModel::Validations::NumericalityValidator.new({ attributes: { value: record.value } }.merge(options))
                                                     .validate_each fake_record, :value, record.value
      record.errors.merge!(fake_record.errors) if fake_record.errors.any?
    end
  end
```

I then used it in my `Setting` model like this:

```ruby
  with_options if: -> { var == 'should_be_positive' } do |on_condition|
    on_condition.validates_with NumericSettingValidator, greater_than: 0
  end
```

Hopefully this can be of use to someone else! It would be nice to have native support for validations in the gem, though - I'm not familiar enough with its source to really understand where the issue with `attribute_changed_in_place?` might be coming from; maybe someone else can help in that regard.

**Comment by Ex-Ark** [comment]
@mashedkeyboard 

Yes, I came across the same thing, basically, due to the lib using cached value ('\--') if the param hasn't changed, you have problem validating it.

Here's a simple fix (that worked in my case)

```ruby
class Setting < RailsSettings::Base
  field :tax_percentage
  field :state

  with_options if: -> { var == 'tax_percentage' } do |on_condition|
    on_condition.validates_numericality_of :value, greater_than: 1, if: :changed?
  end
end
````

**Comment by huacnlee** [comment]
I just release rails-settings-cached 2.5.0 to includes this feature.
